### ISSUE TITLE
Basic relations as singletons

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#118]
The code allows to have several instances of basic relations such as `RelRf` while I'm pretty sure we can use only one (even when refinement has two memory models, base and whole, the program is the same thus the two instances are identical).
This however would not work if we want to analyse two programs (like we did with `porthos`) because the instances of basic relations would differ. So we can to think about potential future uses of the code if we go in this direction.

If we implement such relations using the singleton pattern, I think we can use such relations as "globals" meaning that we can refer to them in any part of the code without relying in the `RelationRepository`.

For example, having that, we might get rid of all the specific getters in `ExecutionGraph` because we can simply call `ExecutionGraph.getEventGraph(RelRf)`.

@ThomasHaas: what do you think?

**Comment by ThomasHaas** [comment]
First of all - as you said - using singletons won't work if we analyze multiple programs simultanously. Also, even for Refinement it makes sense to have different ```RelRf``` since the ```encodeTupleSet``` depends on the axioms which may differ in multiple ```Wmm``` instances. Unless we externalize static analysis information into a different class, we cannot really go down to singletons.

Also, in the case of ```ExecutionGraph```, the specific getters are not needed for the most part. I just added them for convenience cause I imagined that those would be the most common ones to access. In fact, none of them is used right now except the ```CoherenceGraph``` which is special in that it has no associated ```Relation``` object. 
While it is true that you need to rely on ```RelationRepository``` to obtain the ```Relation``` you want (and then possibly use it in ```getEventGraph```), in pretty much all cases you have access to it. Simply because to get ```Relations``` you have to have a ```Wmm``` instance which in turn always has a ```RelationRepository```. 

If you want easier handling of ```Relations```, I would probably add convenience methods to ```Wmm``` that internally access the ```RelationRepository```. In fact, the ```RelationRepository``` seems to be an implementation detail for ```Wmm``` so we might not even want to expose it ever and move all necessary methods to ```Wmm``` instead. And then I don't see much benefit in using e.g. ```.getEventGraph(RelRF)``` vs. something like ```.getEventGraph(wmm.getRelationByName(RF))```

**Comment by hernanponcedeleon** [comment]
> First of all - as you said - using singletons won't work if we analyze multiple programs simultanously. Also, even for Refinement it makes sense to have different `RelRf` since the `encodeTupleSet` depends on the axioms which may differ in multiple `Wmm` instances. Unless we externalize static analysis information into a different class, we cannot really go down to singletons.


You are right about this. I miss the point that the `encodeTupleSets` differ so it seems there is no way we can just use singletons.

> If you want easier handling of `Relations`, I would probably add convenience methods to `Wmm` that internally access the `RelationRepository`. In fact, the `RelationRepository` seems to be an implementation detail for `Wmm` so we might not even want to expose it ever and move all necessary methods to `Wmm` instead. And then I don't see much benefit in using e.g. `.getEventGraph(RelRF)` vs. something like `.getEventGraph(wmm.getRelationByName(RF))`

As you said, without singletons there is no much different between the two methods.
