### ISSUE TITLE
Problem in compilation C11 -> TSO

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#395]
The current compilation from C11 to TSO is broken for (at least) RMW instructions as shown by the litmus test below.
```
C SB-RMW

(*
 * A variant of fhe SB pattern using RMW instructions
 *)

{}

P0 (atomic_int* y, atomic_int* x) {
    int r0 = atomic_fetch_add_explicit(x, 1, memory_order_seq_cst);
    int r1 = atomic_load_explicit(y, memory_order_seq_cst);
}

P1 (atomic_int* y, atomic_int* x) {
    int r0 = atomic_fetch_add_explicit(y, 1, memory_order_seq_cst);
    int r1 = atomic_load_explicit(x, memory_order_seq_cst);
}

exists (0:r1=0 /\ 1:r1=0)
```
Under C11 the behavior is now allowed
```
java -jar dartagnan/target/dartagnan-3.1.1.jar litmus/C11/manual/SB-RMW.litmus --method=assume cat/c11.cat

Condition exists (0:r1==0 && 1:r1==0)
No
Total verification time(ms): 354
```
but under TSO it is
```
java -jar dartagnan/target/dartagnan-3.1.1.jar litmus/C11/manual/SB-RMW.litmus --method=assume cat/tso.cat --target=tso

Condition exists (0:r1==0 && 1:r1==0)
Ok
Total verification time(ms): 458
```

**Comment by ThomasHaas** [comment]
There are two solutions to this problem:
- Add an `mfence` to the compilation scheme of `RMW/XCHG` to avoid reordering.
- Update`tso.cat` to prohibit reordering with rmw events.

The latter solution is IMO the more correct one. The reason is that TSO has no LL/SC and instead uses single atomic instructions to implement RMWs. These atomic instructions have built-in fence semantics, so an actual compiler does not place mfences.
In fact, to implement SC-stores compilers tend to use the XCHG instruction instead of placing an mfence after the store.

**Comment by hernanponcedeleon** [comment]
I just realized `tso.cat` has this relation `let implied = po & W*R & ((M * A) | (A * M))` which contributes to `ghb-tso`. Wouldn't simply adding `Tag.TSO.ATOM` to the loads/stores in the compilation of any atomic HL instruction solve the problem?

**Comment by ThomasHaas** [comment]
Yeah, that should do the trick.
