### ISSUE TITLE
witness validation

### ISSUE THREAD

**Issue by Anthonysdu** [hernanponcedeleon/Dat3M#646]
Hi,

I was trying to use the svcomp script `./Dartagnan-SVCOMP.sh`, however, it outputs

```
Exception in thread "main" java.io.FileNotFoundException: /home/tong/dartagnan/output/main.bpl (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:32)
	at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:97)

```
Are there any other packages need to be installed? Thanks

**Comment by ThomasHaas** [comment]
What parameters did you pass to the script? I think you need to call the script like this:
```
./Dartagnan-SVCOMP.sh -witness <WITNESS_FILE> <PROPERTY_FILE> <PROGRAM_FILE>
```
If you leave out the first `-witness <WITNESS_FILE>`, the script will instead run the standard verification.

I am surprised to see a `main.bpl` in your output because we have switched from boogie code over to llvm code a while ago.

**Comment by Anthonysdu** [comment]
i am using` ./Dartagnan-SVCOMP.sh -witness error-witness.graphml ../sv-benchmarks/c/properties/unreach-call.prp main.c`

and actually it outputs the same for standard verification.

Maybe becasue I am using the svcomp 2023 version?
> I am surprised to see a main.bpl in your output because we have switched from boogie code over to llvm code a while ago.

**Comment by ThomasHaas** [comment]
> i am using` ./Dartagnan-SVCOMP.sh -witness error-witness.graphml ../sv-benchmarks/c/properties/unreach-call.prp main.c`

That looks fine to me.

> Maybe becasue I am using the svcomp 2023 version?
> 
> > I am surprised to see a main.bpl in your output because we have switched from boogie code over to llvm code a while ago.

Did you get that version from our artifact submission (from zenodo?). If so, I would imagine that it should work properly.
If you got this version from an old commit, you might be running into troubles because the old version required SMACK to be installed (which I imagine is contained in the zenodo artifact).
Unless you try to reproduce results with the old version, I would advice you to just build the newest version of dartagnan from sources.

**Comment by hernanponcedeleon** [comment]
If you downloaded the artifact from the svcomp archive 2023 repository, you need to run the artifact on a Linux machine and satisfy the packages listed [here](https://gitlab.com/sosy-lab/benchmarking/fm-tools/-/blame/main/data/dartagnan.yml?ref_type=heads#L25)

**Comment by Anthonysdu** [comment]
many thanks @ThomasHaas and @hernanponcedeleon, I managed to download it in the zenodo artifact and now works fine.
