### ISSUE TITLE
SMT variable creation

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#90]
JavaSMT `FormulaManager` allows directly to create variables of specific types with no need to further access the corresponding type manager.
We can change accesses like `ctx.getFormulaManager().getBooleanFormulaManager().makeVariable(name)` to `ctx.getFormulaManager().makeVariable(BooleanType, name)`.

**Comment by ThomasHaas** [comment]
Where do you see the benefit of this change? As soon as operations are involved, the correct FormulaManager needs to be used anyway. Or do you intend to use ```fmgr.makeApplication```to also change this somehow? I think it might be useful to provide the type when constructing e.g. IConst terms, instead of just a precision value. I don't have any concrete use case in mind though.

Either way, I don't think your changed code exploits the benefit of using a more generic ```makeVariable```call.
Instead of doing code like this:
```
return if precision > -1 ? fmgr.makeVariable(BitVectorType(precision), name) : fmgr.makeVariable(Integer, name)
```
you could now write it like this:
```
FormulaType type = precision > -1 ? BitVectorType(precision) : IntegerType;
return fmgr.makeVariable(type, name);
```
I think the latter is more clean. You might have to use ```FormulaType<?>``` or ```FormulaType<? extends Formula>```for the code to compile.

**Comment by hernanponcedeleon** [comment]
For the time being, the main advantage I see is code compactness and readability (which is became much clear with the last commit implementing your suggestion). Once we have proper typing as in #82, it might be the case we can take even further. 

Anyway, after the last commit, the code is much concise that the `master` version.

**Comment by ThomasHaas** [comment]
Sure. I'm not sure how it will benefit us later, especially because proper typing as in #82 should make it easy to use the appropriate formula manager. But I don't see any disadvantages either, so I'm fine with merging it.
